#assigning pods to nodes through nodeselctor, give label to workernode

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      nodeSelector:
       environment: prod  #labelled to workernode key=value for ip
      containers:
      - name: ip-app
        image: harshajain/ip_app:2
        ports:
        - containerPort: 8080
