pipeline {
    agent any 

    tools {
        maven 'maven-3.9.5'
    }

    stages {
        stage ('Build-Maven') {
            steps {
                sh '''
                    cd ./maven/simple-war/
                    mvn clean package
                    cd ./target/
                    ls
                '''
            }
        }  
    }

}
